export const productInitalValues = {
  name: "",
  category_id: "",
  sub_category_id: "",
  short_description: "",
  long_description: "",
  quantity: "",
  length: "",
  breadth: "",
  height: "",
  quantity_unit: "",
  max_price: 0,
  offer_price: "",
  is_manually_popular: true,
  is_manually_best_choice: true,
  is_delicious: true,
  is_healthy_bites: true,
  is_best_price: true,
  is_deleted: false,
  tags: [],
  nutritions: [{ nutrition_id: '', nutrition_value: '' }],
  stock: 0,
  images: [],
  product_type: "",
  days: 0,
  mfg_date: new Date().toISOString().split("T")[0],  ratings: null,
  options: [],
  meta_title: "",
  meta_description: "",
  meta_keywords: [],
  discount: 0,
};
