
export const productInitalValues = {
    name: " ",
    category_id: "",
    sub_category_id: "",
    short_description: " ",
    long_description: "  ",
    quantity: " ",
    quantity_unit: " ",
    max_price: " ",
    offer_price: " ",
    is_manually_popular: false,
    is_manually_best_choice: false,
    is_delicious: false,
    is_deleted: false,
    tags: [],
    nutritions: [], 
    images: [],
    product_type: " ",
    days: " ",
    mfg_date: " ",
    ratings: null,
    options: [],
    meta_title: " ",
    meta_description: " ",
    meta_keywords:[],
};